apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: {{ .Release.Name }}-{{ .Values.component.name }}
  labels:
    oda.tmforum.org/componentName: {{ .Release.Name }}-{{ .Values.component.name }}
    {{- include "geographicaddress.labels" . | nindent 4 }}
spec:
  componentMetadata:
    id: {{ .Values.component.id }}
    name: {{ .Values.component.name }}
    functionalBlock: {{ .Values.component.functionalBlock }}
    publicationDate: {{ .Values.component.publicationDate }}
    status: specified
    version: {{ .Values.component.version }}
    description: "TMF673 Geographic Address Management ODA Component - Provides standardized client interface to an Address management system for worldwide addresses."
    maintainers:
    - name: ODA Component Team
      email: component-team@example.com
    owners:
    - name: ODA Component Team
      email: component-team@example.com

  coreFunction:
    exposedAPIs:
    - name: geographicaddressmanagement
      specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.0.swagger.json"
      implementation: {{ .Release.Name }}-geographicaddressapi
      apiType: openapi
      id: TMF673
      gatewayConfiguration:
        apiKeyVerification: {{- .Values.component.apipolicy.apiKeyVerification | toYaml | nindent 10 }}
        rateLimit: {{- .Values.component.apipolicy.rateLimit | toYaml | nindent 10 }}
        quota: {{- .Values.component.apipolicy.quota | toYaml | nindent 10 }}
        OASValidation: {{- .Values.component.apipolicy.OASValidation | toYaml | nindent 10 }}
        CORS: {{- .Values.component.apipolicy.CORS | toYaml | nindent 10 }}
        template: "{{ .Values.component.apipolicy.template }}"
      path: /{{ .Release.Name }}-{{ .Values.component.name }}/tmf-api/geographicAddressManagement/v4
      developerUI: /{{ .Release.Name }}-{{ .Values.component.name }}/tmf-api/geographicAddressManagement/v4/docs
      port: {{ .Values.api.service.port }}

    dependentAPIs: []

  eventNotification:
    publishedEvents:
    - name: GeographicAddressCreateEvent
      specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.0.swagger.json"
      apiType: openapi
      implementation: {{ .Release.Name }}-geographicaddressapi
      port: {{ .Values.api.service.port }}
    - name: GeographicAddressAttributeValueChangeEvent
      specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.0.swagger.json"
      apiType: openapi
      implementation: {{ .Release.Name }}-geographicaddressapi
      port: {{ .Values.api.service.port }}
    - name: GeographicAddressStateChangeEvent
      specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.0.swagger.json"
      apiType: openapi
      implementation: {{ .Release.Name }}-geographicaddressapi
      port: {{ .Values.api.service.port }}
    - name: GeographicAddressDeleteEvent
      specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.0.swagger.json"
      apiType: openapi
      implementation: {{ .Release.Name }}-geographicaddressapi
      port: {{ .Values.api.service.port }}
    subscribedEvents: []

  managementFunction:
    exposedAPIs: []

  securityFunction:
    canvasSystemRole: {{ .Values.security.canvasSystemRole }}
    exposedAPIs: []
