apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-geographicaddressapi
  labels:
    {{- include "geographicaddress.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-{{ .Values.component.name }}
    component: geographicaddressapi
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    impl: {{ .Release.Name }}-geographicaddressapi
